"""
모노그래프 챕터(.txt) → OpenAI → Neo4j MERGE Cypher, 소스 파일 옆에 .cypher.txt 로 저장.

- 기본 모델: gpt-4o. --model 로 o1 등 다른 모델로 변경 가능.
- 전역 herb_id / formula_id: 스크립트가 부여 후 프롬프트에 주입.
  주 Herb 노드는 MERGE 키로 `name`만 사용하고, `herb_id`는 ON CREATE/MATCH SET으로 속성만 갱신.
- 긴 본문은 tiktoken 기준 줄 단위 청크로 분할 후 순차 호출.
- 응답이 출력 한도로 잘리면 API가 finish_reason=length 로 알려주며, 스크립트가 .cypher.txt 안에
  WARNING 주석과 터미널 경고를 남긴다. 그때는 --max-completion-tokens 를 키우거나 청크를 줄인 뒤 재생성.

실행 (프로젝트 루트):
  python scripts/monograph_to_cypher_txt.py --dry-run
  python scripts/monograph_to_cypher_txt.py --max-files 1

OPENAI_API_KEY 는 환경변수 또는 프로젝트 루트 .env 에 설정.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import time
from pathlib import Path

try:
    import tiktoken
except ImportError:
    tiktoken = None  # type: ignore[misc, assignment]

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None  # type: ignore[misc, assignment]

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None  # type: ignore[misc, assignment]


SYSTEM_PROMPT = """당신은 한약 모노그래프 텍스트를 Palantiny Neo4j 스키마에 맞는 Cypher로만 변환한다.
You are an expert Neo4j Cypher Query Engineer specializing in Traditional Korean Medicine (TKM) Knowledge Graphs for the 'Palantiny' project. 
Your task is to parse unstructured TKM monograph text and convert it into strictly formatted Neo4j Cypher scripts using `MERGE` statements.

출력 규칙:
- 출력은 Cypher 문장만. 마크다운, 코드펜스(```), 설명 문장 금지.
- 모든 노드 생성은 MERGE 만 사용. CREATE 금지.
- 주석은 // 로 짧게만 가능.
- 완결된 Cypher 문(실행 단위)마다 끝에 세미콜론(;)을 붙인다. MERGE … ON CREATE SET … ON MATCH SET … 은 한 문장이므로, ON MATCH SET 까지 쓴 뒤 그 묶음 끝에만 ; 를 붙인다(MERGE와 ON 절 사이에는 ; 를 넣지 않는다).

[CRITICAL INTEGRATION RULE]
To ensure perfect integration with our commerce database, the `Herb` node MUST be merged ONLY by its `name`. The `herb_id` must be assigned using `ON CREATE SET` and `ON MATCH SET`.
WRONG: MERGE (h:Herb {herb_id: 'H_054'})
CORRECT: MERGE (h:Herb {name: '형개'})

노드 라벨 및 속성:
- Herb: herb_id (문자열, 이 한약재의 고유 키. 사용자가 지정한 값만 사용), name, synonyms (문자열 리스트), toxicity (문자열, 예: 무독)
- NatureTemp: name (한글, 예: 한/열/온/량/평)
- NatureTaste: name (한글, 예: 감/신/고/산/함)
- Meridian: name (한글, 예: 비/위/간)
- Efficacy: name (한글 효능 요약)
- Symptom: name (한글 증상·병증명)
- Formula: formula_id (문자열 F_NNN 형식, 사용자가 지정한 범위만 사용), name (한글 방명)

관계:
- (Herb)-[:HAS_TEMP]->(NatureTemp)
- (Herb)-[:HAS_TASTE]->(NatureTaste)
- (Herb)-[:ACTS_ON]->(Meridian)
- (Herb)-[:HAS_EFFICACY]->(Efficacy)
- (Herb)-[:TREATS]->(Symptom)
- (Formula)-[:CONTAINS]->(Herb)
- 문서에 상극·금기가 명시되면 (Herb)-[:CONTRAINDICATES {type, reason?}]->(Herb 또는 Symptom) 도 MERGE 로 표현 가능

처방 구성 약재는 herb_id 가 없으면 MERGE (x:Herb {name: '한글명'}) 만 사용해도 된다.

예시:

// auto-generated by monograph_to_cypher_txt.py
// source: vol05/형개.txt
// herb_id: H_054
// model: gpt-4o, chunks: 1

// --- chunk 1/1 ---
// 수정된 코드 (완벽한 통합용)
MERGE (h:Herb {name: '형개'})
ON CREATE SET h.herb_id = 'H_054', 
              h.synonyms = ['荊芥穗', '姜芥', '薑芥'], 
              h.toxicity = '무독'
ON MATCH SET  h.herb_id = 'H_054', 
              h.synonyms = ['荊芥穗', '姜芥', '薑芥'], 
              h.toxicity = '무독'

MERGE (nt:NatureTemp {name: '온'})
MERGE (ta:NatureTaste {name: '신'})

MERGE (h)-[:HAS_TEMP]->(nt)
MERGE (h)-[:HAS_TASTE]->(ta)

MERGE (m1:Meridian {name: '폐'})
MERGE (m2:Meridian {name: '간'})

MERGE (h)-[:ACTS_ON]->(m1)
MERGE (h)-[:ACTS_ON]->(m2)

MERGE (e1:Efficacy {name: '해표산풍'})
MERGE (e2:Efficacy {name: '투진'})

MERGE (h)-[:HAS_EFFICACY]->(e1)
MERGE (h)-[:HAS_EFFICACY]->(e2)

MERGE (s1:Symptom {name: '감모'})
MERGE (s2:Symptom {name: '두통'})
MERGE (s3:Symptom {name: '두통목적'})
MERGE (s4:Symptom {name: '마진투발불창'})
MERGE (s5:Symptom {name: '창양초기'})
MERGE (s6:Symptom {name: '풍진'})

MERGE (h)-[:TREATS]->(s1)
MERGE (h)-[:TREATS]->(s2)
MERGE (h)-[:TREATS]->(s3)
MERGE (h)-[:TREATS]->(s4)
MERGE (h)-[:TREATS]->(s5)
MERGE (h)-[:TREATS]->(s6)

MERGE (sym_contra:Symptom {name: '표허유한'})
MERGE (h)-[:CONTRAINDICATES {type: '금기', reason: '표허유한 및 발열이 중하고 악한이 경한 경우'}]->(sym_contra)

MERGE (f1:Formula {formula_id: 'F_014', name: '소풍산'})
MERGE (f1)-[:CONTAINS]->(h)
MERGE (herb_gc:Herb {name: '감초'})
MERGE (herb_gs:Herb {name: '고삼'})
MERGE (herb_dg:Herb {name: '당귀'})
MERGE (herb_mt:Herb {name: '목통'})
MERGE (herb_bf:Herb {name: '방풍'})
MERGE (herb_sj:Herb {name: '생지'})
MERGE (herb_sg:Herb {name: '석고'})
MERGE (herb_st:Herb {name: '선태'})
MERGE (herb_ub:Herb {name: '우방자'})
MERGE (herb_zm:Herb {name: '지모'})
MERGE (herb_cc:Herb {name: '창출'})
MERGE (herb_hm:Herb {name: '호마'})

MERGE (f1)-[:CONTAINS]->(herb_gc)
MERGE (f1)-[:CONTAINS]->(herb_gs)
MERGE (f1)-[:CONTAINS]->(herb_dg)
MERGE (f1)-[:CONTAINS]->(herb_mt)
MERGE (f1)-[:CONTAINS]->(herb_bf)
MERGE (f1)-[:CONTAINS]->(herb_sj)
MERGE (f1)-[:CONTAINS]->(herb_sg)
MERGE (f1)-[:CONTAINS]->(herb_st)
MERGE (f1)-[:CONTAINS]->(herb_ub)
MERGE (f1)-[:CONTAINS]->(herb_zm)
MERGE (f1)-[:CONTAINS]->(herb_cc)
MERGE (f1)-[:CONTAINS]->(herb_hm)


한국어 이름·용어를 우선한다. 모노그래프에 근거하지 않은 사실을 지어내지 않는다."""


FORMULA_ID_RE = re.compile(r'formula_id\s*:\s*[\'"]F_(\d+)[\'"]', re.IGNORECASE)

# Chat Completions 에서 temperature 등이 제한되는 모델 (소문자 비교)
_REASONING_STYLE_PREFIXES = ("o1", "o2", "o3", "o4", "gpt-5")


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _is_reasoning_style_model(model: str) -> bool:
    m = model.strip().lower()
    return any(m == p or m.startswith(p + "-") for p in _REASONING_STYLE_PREFIXES)


def _sorted_chapter_sources(root: Path) -> list[Path]:
    files: list[Path] = []
    for p in root.rglob("*.txt"):
        if p.name.endswith(".cypher.txt"):
            continue
        files.append(p)

    def sort_key(p: Path) -> tuple[int, str]:
        m = re.match(r"vol(\d+)", p.parent.name, re.IGNORECASE)
        vol = int(m.group(1)) if m else 999
        return (vol, p.name)

    files.sort(key=sort_key)
    return files


def _format_h_id(n: int, width: int) -> str:
    return f"H_{n:0{width}d}"


def _format_f_id(n: int, width: int) -> str:
    return f"F_{n:0{width}d}"


def _get_encoding(model: str):
    if tiktoken is None:
        raise RuntimeError("tiktoken 이 필요합니다. pip install tiktoken")
    try:
        return tiktoken.encoding_for_model(model)
    except KeyError:
        return tiktoken.get_encoding("cl100k_base")


def _split_long_line(line: str, enc, max_tokens: int) -> list[str]:
    if len(enc.encode(line)) <= max_tokens:
        return [line]
    out: list[str] = []
    start = 0
    n = len(line)
    while start < n:
        lo, hi = start + 1, n
        best = start + 1
        while lo <= hi:
            mid = (lo + hi) // 2
            chunk = line[start:mid]
            if len(enc.encode(chunk)) <= max_tokens:
                best = mid
                lo = mid + 1
            else:
                hi = mid - 1
        if best <= start:
            best = start + 1
        out.append(line[start:best])
        start = best
    return out


def chunk_text_by_tokens(text: str, enc, max_tokens: int) -> list[str]:
    segments: list[str] = []
    for line in text.split("\n"):
        segments.extend(_split_long_line(line, enc, max_tokens))

    chunks: list[str] = []
    buf: list[str] = []
    cur = 0
    for seg in segments:
        add = len(enc.encode(seg)) + (1 if buf else 0)
        if buf and cur + add > max_tokens:
            chunks.append("\n".join(buf))
            buf = [seg]
            cur = len(enc.encode(seg))
        else:
            buf.append(seg)
            cur += add
    if buf:
        chunks.append("\n".join(buf))
    return chunks if chunks else [""]


def _strip_code_fences(text: str) -> str:
    s = text.strip()
    if s.startswith("```"):
        s = re.sub(r"^```(?:cypher)?\s*", "", s, flags=re.IGNORECASE)
        s = re.sub(r"\s*```\s*$", "", s)
    return s.strip()


def _max_formula_num(text: str) -> int | None:
    nums = [int(m.group(1)) for m in FORMULA_ID_RE.finditer(text)]
    return max(nums) if nums else None


def _build_user_message(
    *,
    herb_name: str,
    herb_id: str,
    rel_path: str,
    chunk_index: int,
    chunk_total: int,
    next_formula_id: str,
    is_first_chunk: bool,
    body: str,
) -> str:
    part_rule = (
        "이번 출력은 이 한약재 전체 중 세그먼트 "
        f"{chunk_index}/{chunk_total} 에 해당하는 본문만 반영한다.\n"
    )
    if is_first_chunk:
        herb_rule = (
            "주 한약재(Herb)는 반드시 name으로만 MERGE 한다. MERGE 조건에 herb_id 를 넣지 않는다.\n"
            f"첫 세그먼트에서는 다음 형태를 따른다:\n"
            f"MERGE (h:Herb {{name: '{herb_name}'}})\n"
            f"ON CREATE SET h.herb_id = '{herb_id}', h.synonyms = [...], h.toxicity = '...' "
            f"(synonyms·toxicity는 모노그래프 근거)\n"
            f"ON MATCH SET h.herb_id = '{herb_id}', h.synonyms = [...], h.toxicity = '...' "
            f"(ON CREATE와 동일한 속성으로 맞춤)\n"
        )
    else:
        herb_rule = (
            f"주 한약재는 이미 존재한다. MERGE (h:Herb {{name: '{herb_name}'}}) 로만 h를 묶은 뒤, "
            "이번 세그먼트 본문에만 근거한 추가 MERGE 만 출력한다. "
            "첫 세그먼트에서 쓴 Herb에 대한 ON CREATE SET / ON MATCH SET 블록은 반복하지 않는다.\n"
        )

    formula_rule = (
        f"새 Formula 노드에 부여하는 formula_id 는 '{next_formula_id}' 부터 순서대로만 사용한다. "
        "이미 앞 세그먼트에서 다룬 처방은 반복하지 않는다. "
        "출력하는 완결된 Cypher 문마다 끝에 세미콜론(;)을 붙인다( MERGE+ON CREATE+ON MATCH 묶음은 한 문장 끝에만 ; ).\n"
    )

    return (
        f"[파일] {rel_path}\n"
        f"[주 한약재 name — MERGE 키] '{herb_name}'\n"
        f"[부여 herb_id — ON CREATE/MATCH SET 의 h.herb_id 만, MERGE 키 아님] '{herb_id}'\n"
        + part_rule
        + herb_rule
        + formula_rule
        + "\n[모노그래프 본문]\n"
        + body
    )


def _build_messages(model: str, user_content: str) -> list[dict[str, str]]:
    """o1 등 추론 모델은 system 역할 제약이 있을 수 있어 user 한 통으로 합친다."""
    if _is_reasoning_style_model(model):
        return [
            {
                "role": "user",
                "content": (
                    "[시스템 지침 — 반드시 준수]\n"
                    + SYSTEM_PROMPT
                    + "\n\n---\n\n[작업 요청]\n"
                    + user_content
                ),
            },
        ]
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def _chat_create(
    client: "OpenAI",
    *,
    model: str,
    messages: list[dict[str, str]],
    max_completion_tokens: int,
    temperature: float,
):
    """o1 등은 API가 max_tokens를 거부하고 max_completion_tokens만 허용 → 먼저 그걸 시도."""
    kwargs: dict = {"model": model, "messages": messages}
    if not _is_reasoning_style_model(model):
        kwargs["temperature"] = temperature
    try:
        return client.chat.completions.create(
            **kwargs,
            max_completion_tokens=max_completion_tokens,
        )
    except TypeError as e:
        err = str(e).lower()
        if "max_completion" not in err and "unexpected keyword" not in err:
            raise
        if _is_reasoning_style_model(model):
            raise RuntimeError(
                "o1 등 추론 모델은 max_completion_tokens가 필요합니다. "
                "설치된 openai 패키지가 이 인자를 지원하지 않습니다. "
                'pip install -U "openai>=1.40" 후 다시 실행하세요.'
            ) from e
        return client.chat.completions.create(
            **kwargs,
            max_tokens=max_completion_tokens,
        )


def run_file(
    client: "OpenAI",
    *,
    path: Path,
    chapters_root: Path,
    herb_name: str,
    herb_id: str,
    model: str,
    max_chunk_tokens: int,
    max_completion_tokens: int,
    temperature: float,
    sleep_s: float,
    formula_num: int,
    id_width: int,
) -> tuple[str, int]:
    enc = _get_encoding(model)
    raw = path.read_text(encoding="utf-8")
    chunks = chunk_text_by_tokens(raw, enc, max_chunk_tokens)
    rel = str(path.relative_to(chapters_root)).replace("\\", "/")

    parts: list[str] = [
        "// auto-generated by monograph_to_cypher_txt.py",
        f"// source: {rel}",
        f"// herb_name (MERGE 키): {herb_name}",
        f"// herb_id (속성): {herb_id}",
        f"// model: {model}, chunks: {len(chunks)}",
        "",
    ]

    next_f = formula_num
    for i, body in enumerate(chunks, start=1):
        next_formula_str = _format_f_id(next_f, id_width)
        user = _build_user_message(
            herb_name=herb_name,
            herb_id=herb_id,
            rel_path=rel,
            chunk_index=i,
            chunk_total=len(chunks),
            next_formula_id=next_formula_str,
            is_first_chunk=(i == 1),
            body=body,
        )
        messages = _build_messages(model, user)
        resp = _chat_create(
            client,
            model=model,
            messages=messages,
            max_completion_tokens=max_completion_tokens,
            temperature=temperature,
        )
        ch0 = resp.choices[0]
        choice = ch0.message.content or ""
        cy = _strip_code_fences(choice)
        parts.append(f"// --- chunk {i}/{len(chunks)} ---")
        finish = getattr(ch0, "finish_reason", None)
        if finish == "length":
            parts.append(
                "// WARNING: 출력 토큰 한도로 응답이 잘렸습니다(finish_reason=length). "
                "Cypher가 불완전할 수 있습니다. 같은 명령에 --max-completion-tokens 를 키우거나 "
                "--max-chunk-tokens 를 줄여 다시 생성하세요."
            )
            print(
                f"[경고] {rel} chunk {i}/{len(chunks)}: 출력 한도로 잘림 → "
                f"--max-completion-tokens 증가 권장 (현재 {max_completion_tokens})",
                file=sys.stderr,
            )
        parts.append(cy)
        parts.append("")

        mmax = _max_formula_num(cy)
        if mmax is not None and mmax >= next_f:
            next_f = mmax + 1

        if sleep_s > 0:
            time.sleep(sleep_s)

    return "\n".join(parts).rstrip() + "\n", next_f


def main() -> int:
    parser = argparse.ArgumentParser(description="모노그래프 → OpenAI(gpt-4o 기본) → 옆 .cypher.txt")
    parser.add_argument(
        "--chapters-root",
        type=Path,
        default=_repo_root() / "data" / "herb_monograph_chapters",
        help="volNN/약재.txt 가 있는 루트",
    )
    parser.add_argument(
        "--model",
        default="gpt-4o",
        help="Chat Completions 모델 (기본: gpt-4o). 예: gpt-4o-mini, o1",
    )
    parser.add_argument(
        "--start-herb-num",
        type=int,
        default=5,
        help="첫 파일에 부여할 H 번호 (init_data H_004 다음이면 5)",
    )
    parser.add_argument(
        "--start-formula-num",
        type=int,
        default=12,
        help="첫 Formula 시작 번호 (init_data F_011 다음이면 12)",
    )
    parser.add_argument("--id-width", type=int, default=3, help="H_001 / F_001 자릿수")
    parser.add_argument(
        "--max-chunk-tokens",
        type=int,
        default=6000,
        help="프롬프트 본문 청크 상한(토큰, 대략)",
    )
    parser.add_argument(
        "--max-completion-tokens",
        type=int,
        default=8192,
        help="모델 응답 토큰 상한 (o1 등은 추론 포함해 더 크게, 예: 25000)",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.2,
        help="비추론 모델에만 적용 (o1 등은 API에서 무시되거나 생략됨)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="청크 사이 초 단위 대기",
    )
    parser.add_argument("--max-files", type=int, default=0, help="0이면 전부, N이면 앞에서 N개만")
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help=".cypher.txt 가 있으면 API 호출 생략",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="herb_id 할당만 출력",
    )
    args = parser.parse_args()

    if load_dotenv is not None:
        load_dotenv(_repo_root() / ".env")

    root: Path = args.chapters_root.resolve()
    if not root.is_dir():
        print(f"[오류] 폴더 없음: {root}", file=sys.stderr)
        return 1

    sources = _sorted_chapter_sources(root)
    if not sources:
        print(f"[오류] 소스 .txt 없음: {root}", file=sys.stderr)
        return 1

    if args.max_files > 0:
        sources = sources[: args.max_files]

    herb_num = args.start_herb_num
    next_formula = args.start_formula_num
    width = args.id_width

    if args.dry_run:
        print(f"[dry-run] model={args.model} files={len(sources)} (vol 순, 파일명 순)")
        for p in sources:
            hid = _format_h_id(herb_num, width)
            rel = p.relative_to(root)
            print(f"  {hid}  name={p.stem}  <-  {rel}")
            herb_num += 1
        print(f"[dry-run] 다음 배치 제안 --start-herb-num {herb_num}")
        return 0

    if OpenAI is None:
        print("[오류] openai 패키지가 필요합니다.", file=sys.stderr)
        return 1
    if not os.environ.get("OPENAI_API_KEY"):
        print("[오류] OPENAI_API_KEY 가 없습니다 (.env 또는 환경변수).", file=sys.stderr)
        return 1

    client = OpenAI()

    for p in sources:
        hid = _format_h_id(herb_num, width)
        out_path = p.with_name(f"{p.stem}.cypher.txt")

        if args.skip_existing and out_path.is_file():
            print(f"[건너뜀] 존재: {out_path.name}")
            herb_num += 1
            continue

        print(
            f"[생성] {hid}  name={p.stem}  {p.relative_to(root)}  →  {out_path.name}  "
            f"(F≥{_format_f_id(next_formula, width)})"
        )
        try:
            text, next_formula = run_file(
                client,
                path=p,
                chapters_root=root,
                herb_name=p.stem,
                herb_id=hid,
                model=args.model,
                max_chunk_tokens=args.max_chunk_tokens,
                max_completion_tokens=args.max_completion_tokens,
                temperature=args.temperature,
                sleep_s=args.sleep,
                formula_num=next_formula,
                id_width=width,
            )
        except Exception as e:
            print(f"[실패] {p}: {e}", file=sys.stderr)
            return 1

        out_path.write_text(text, encoding="utf-8")
        herb_num += 1

    print(f"[완료] 다음 배치용: --start-herb-num {herb_num} --start-formula-num {next_formula}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
